dashboard/urls.py
#!/usr/bin/env python
# set coding: utf-8
# @Time : 2020/7/24 15:09
# @File : urls.py
# @Author : richard zhu
# @purpose :

from django.urls import path, include, re_path
from dashboard.views import (GroupListView,
                             GroupDelete,
                             GroupUpdate,
                             ItemList,
                             ItemView,
                             FieldsView)
app_name="dashboard"
urlpatterns = [
    path("", GroupListView.as_view(), name='group'),
    path("group/", GroupListView.as_view(), name='group'),
    path("group/<int:pk>/update", GroupUpdate.as_view(), name='group-update'),
    path("group/<int:pk>/delete", GroupDelete.as_view(), name='group-delete'),
    path("item/list/", ItemList.as_view(), name='item-list'),  # item列表
    path("item/", ItemView.as_view(), name='item'), # item的crud
    path("fields/", FieldsView.as_view(), name='fields')

]



webKeepass/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.views import static  as view_static
from django.conf import settings
from portal.views import LogoutView, LoginView, bad_request, page_not_found

urlpatterns = [
    path('%s/' % settings.ADMIN_URL, admin.site.urls, name='admin'),  # 安全措施，防止admin外泄
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', include('dashboard.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/image/favicon.ico'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG == False:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', view_static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
    ]

handler400 = bad_request
handler404 = page_not_found

templates/fields.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fields</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.6.3/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/ionicons-2.0.1/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
</head>
<body>
<div class="wrapper" style="width: 95%; margin-left: 20px; margin-top: 20px">
    <div class="box box-primary">
        <div class="box-body">
            <form method="post" action="{% url 'dashboard:fields' %}?item_id={{ item_id }}" role="form" id="fieldsForm">
                {% csrf_token %}
                <div class="form-group" id="add-fields">
                    <div class="row" >
                        <div class="col-xs-5">
                            <label class="control-label">Name</label>
                        </div>
                        <div class="col-xs-5">
                            <label class="control-label">Value</label>
                        </div>
                    </div>
                        {% for each_field in fields %}
                        <div class="row fields" >
                            <div class="col-xs-5">
                                <input type="text" name="key" value="{{ each_field.key }}"  class="form-control">
                            </div>
                            <div class="col-xs-5">
                                <input type="text" name="value" value="{{ each_field.value }}" class="form-control">
                            </div>
                            <div class="col-xs-1">
                                <a href="#" onclick="delInput(this)"><span class="glyphicon glyphicon-minus"></span></a>
                            </div>
                            <hr>
                        </div>
                        {% endfor %}
                        <div class="row fields" >
                            <div class="col-xs-5">
                                <input type="text" name="key"  class="form-control">
                            </div>
                            <div class="col-xs-5">
                                <input type="text" name="value"  class="form-control">
                            </div>
                            <div class="col-xs-1">
                                <a href="#" onclick="addInputReturn(this)"><span class="glyphicon glyphicon-plus"></span></a>
                            </div>
                            <hr>
                        </div>
                </div>

                <div class="box-footer ">
                    <button class="btn btn-success" id="btn-submit" type="button" >保存</button>
                    <button class="btn btn-danger" id="back" href="" type="button">返回</button>
                </div>
            </form>
        </div>
    </div>
    <script src="{%  static 'plugins/jQuery/jquery-2.2.3.min.js' %}" ></script>
    <script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}"></script>
    <script src="{%  static 'dist/js/app.min.js' %}"></script>
    <script src="{%  static 'bootstrap/js/bootstrap.min.js' %}" ></script>
    <script>

        //TODO 增加遮罩，控制window只弹出一次

        $(document).ready(function () {
            $('#btn-submit').click(function () {
                $('#fieldsForm').submit();
                alert("修改成功")
            });

            $('#back').click(function () {
                window.close();
            })
        });

        function delInput(that) {
            $(that).parent().parent().remove();
        }

        function addInputReturn(that) {
                //添加减号
                var $content = "";
                $content += '<a href="#" onclick="delInput(this)" >';
                $content += '<span class="glyphicon glyphicon-minus"></span>';
                $content += '</a>';
                $(that).parent().append($content);

                //去除加号
                that.remove();

                //增加标签
                var html = "";
                html += '<div class="row fields" id=>'
                html += '<div class="col-xs-5">'
                html += '<input type="text" name="key"   class="form-control">'
                html += '</div>'
                html += '<div class="col-xs-5">'
                html += '<input type="text" name="value"  class="form-control">'
                html += '</div>'
                html += '<div class="col-xs-1">'
                html += '<a href="#" id="dynamic" onclick="addInputReturn(this)"><span class="glyphicon glyphicon-plus"></span></a>'
                html += '</div>'
                html += '<hr>'
                html += '</div>'
                $("#add-fields").last().append(html);
        }

    </script>
</body>
</html>

templates/groupList.html
{% extends 'portal/base.html' %}
{% load static %}
{% load mytags %}
{% block title %}密码组{% endblock %}

{% block css %}
    <link href="{% static 'index.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            密码组
            <small>ItemGroup List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li class="active">密码组</li>
        </ol>
        <hr />
    </section>

    <section class="content">
        <div class="table">
            <table>
                <tr>
                    <td><button data-toggle="modal" data-target="#createGroupModal" class="btn btn-success">新增</button></td>
                </tr>
            </table>
        </div>

        <div class="table-responsive">
            <table id="item_group_table" class="my_table table table-hover table-bordered table-striped">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>组名</th>
                        <th>密码条数</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ig in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'dashboard:item-list' %}?gid={{ ig.id }}">{{ ig.name }}</a></td>
                            <td>{{ ig.id|items_cnt }}</td>
                            <td>
                                <button type="button" data-toggle="modal"
                                        data-target="#editGroupModal"
                                        class="btn btn-warning btn-cn-edit" name="{{ ig.name }}" id="{{ ig.id }}">编辑</button>
                                <button type="button" class="btn btn-danger btn-cn-delete" id="{{ ig.id }}">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>

        {# 新建模态框 #}
        <div class="modal fade" id="createGroupModal" tabindex="-1" role="dialog" aria-labelledby="createGroupModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">创建密码组</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'dashboard:group' %}" id="CreateItemGroupForm">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" class="btn btn-primary" onclick="createFormSubmit()" id="createItemGroup">提交</button>
                    </div>
                </div>
            </div>
        </div>

        {# 编辑模态框 #}
        <div class="modal fade" id="editGroupModal" tabindex="-1" role="dialog" aria-labelledby="editGroupModal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">修改密码组</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form method="post" id="editItemGroupForm">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Name:</label>
                                <input type="text" class="input-lg" autofocus id="editInputName" >
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" class="btn btn-primary"  id="editSubmit">提交</button>
                    </div>
                </div>
            </div>

        </div>
    </section>

{% endblock %}


{% block script %}

    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <script>
        $(function () {
            $('#item_group_table').DataTable({
              "paging": true,       <!-- 允许分页 -->
              "lengthChange": true, <!-- 允许改变每页显示的行数 -->
              "searching": true,    <!-- 允许内容搜索 -->
              "ordering": true,     <!-- 允许排序 -->
              "info": true,         <!-- 显示信息 -->
              "autoWidth": true
            });
        });
    </script>

    <script>

        function createFormSubmit() {
            $('#CreateItemGroupForm').submit();
        };

        $(document).ready(function () {
            $('#editSubmit').click(function () {
                var gid = $(this).attr("gid");
                var new_name = $('#editInputName').val()
                $.ajax({
                    url: "{% url 'dashboard:group-update' 123 %}".replace('123', gid),
                    type: 'POST',
                    data: {"name": new_name},
                    success: function () {
                        alert("更新成功");
                        window.location.reload();
                    },
                    error: function (e) {
                        alert("更新失败，原因："+e);
                    }
                 });
            })

            $('.btn-cn-edit').click(function () {
                var name = $(this).attr("name");
                var gid = $(this).attr("id");
                var url = "{% url 'dashboard:group-update' 123 %}".replace(123, gid)
                $('#editInputName').attr("value", name);
                $('#editSubmit').attr("gid", gid);
                {#$('#editItemGroupForm').attr("action", url);#}
            });

            $('.btn-cn-delete').click(function () {
                var gid = $(this).attr("id");
                if(delConfirm()){
                    $.ajax({
                        url: "{% url 'dashboard:group-delete' 123 %}".replace('123', gid),
                        type: 'DELETE',
                        success: function () {
                            window.location.reload();
                        },
                        error: function (data) {
                            alert("删除失败,原因：" + data.statusText);
                        }
                    });
                }else{
                    return
                }

            });

        });


    </script>

{% endblock %}

templates/itemCreate.html
{% extends 'portal/base.html' %}
{% load static %}
{% load mytags %}
{% load bootstrap %}
{% block title %}创建密码{% endblock %}

{% block content %}
    <section class="content-header"></section>
    <section class="content">
    <div class="wrapper" style="width: 50%">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3>创建</h3>
            </div>

            <form role="form" method="post" action="{% url 'dashboard:item' %}" class="form-horizontal">
                {% csrf_token %}
                <div class="box-body" >
                    {{ itemf | bootstrap_horizontal }}
                </div>
                <div class="box-footer ">
                    <button class="btn btn-success" type="submit" >保存</button>
                    <button class="btn btn-danger" id="back" type="button">返回</button>
                </div>
            </form>
        </div>
    </div>
    </section>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            $('#back').click(function () {
               window.location.href = "{% url 'dashboard:item-list' %}";
            });
        })
    </script>
{% endblock %}

templates/itemList.html
{% extends 'portal/base.html' %}
{% load static %}
{% load mytags %}
{% block title %}密码条目管理{% endblock %}

{% block css %}
    <link href="{% static 'index.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <section class="content-header">
    <h1>
        密码条目
        <small>Item List</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">密码条目</li>
    </ol>
    <hr />
    </section>

    <section class="content">
        <div class="row" style="margin-bottom: 20px">
            <a id="item_create" style="margin-left: 15px" class="btn btn-success" href="{% url 'dashboard:item' %}">新增</a>
        </div>
        <div class="table-responsive">
            <table id="item_table" class="my_table table table-hover table-bordered table-striped">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>名字</th>
                        <th>所属组</th>
                        <th>用户名</th>
                        <th>密码</th>
                        <th>URL</th>
                        <th>备注</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ item.title }}</td>
                            <td>{{ item.group.name }}</td>
                            <td>
                                <p data-role="username" data-clipboard-text="{{ item.username }}">{{ item.username }}</p>
                            </td>
                            <td>
                                <p data-role='passwd' data-clipboard-text="{{ item.password|passwd2str }}">{{ item.password|pwd2fake }}</p>
                            </td>
                            <td>
                                <p data-role="url" data-clipboard-text="{{ item.url }}">{{ item.url }}</p>
                            </td>
                            <td>{{ item.comment }}</td>
                            <td>
                                <span class="hidden">{{ item.id }}</span>
                                <button type="button" data-toggle="modal"
                                        data-role="btn-cn-fields"
                                        class="btn btn-success" item_id="{{ item.id }}" >EntryFields</button>
                                <a href="{% url 'dashboard:item'%}?id={{ item.id }}"><button type="button" class="btn btn-warning" >编辑</button></a>
                                <button type="button" data-role="delete-item" id="{{ item.id }}" class="btn btn-danger">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
      </div>

    </section>

{% endblock %}

{% block script %}

    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'clipboard.min.js' %}"></script>
    <script>
        $(function () {
            $('#item_table').DataTable({
              "paging": true,       <!-- 允许分页 -->
              "lengthChange": true, <!-- 允许改变每页显示的行数 -->
              "searching": true,    <!-- 允许内容搜索 -->
              "ordering": true,     <!-- 允许排序 -->
              "info": true,         <!-- 显示信息 -->
              "autoWidth": true
            });
        });
    </script>

    <script>
        var klass={
            init: function () {
                this.table = $('#item_table');
                this.initTable();
            },
            initTable: function () {
                this.table.on('click', '[data-role="passwd"]', function () {
                    var clipboard = new ClipboardJS(this);
                    clipboard.on('error', function (e) {
                        console.log('error',e)
                    });
                });


                this.table.on('click', '[data-role="username"]', function () {
                    var clipboard = new ClipboardJS(this);
                    clipboard.on('error', function (e) {
                        console.log('error',e)
                    });
                });

                this.table.on('click', '[data-role="url"]', function () {
                    var clipboard = new ClipboardJS(this);
                    clipboard.on('error', function (e) {
                        console.log('error',e)
                    })
                });

                this.table.on('click', '[data-role="delete-item"]', function () {
                    var id = $(this).attr("id");
                    if(delConfirm()){
                        $.ajax({
                            url: "{% url 'dashboard:item'%}?id="+id,
                            type: 'delete',
                            success: function () {
                                window.location.reload();
                            },
                            error: function (data) {
                                alert("删除失败,原因：" + data.statusText);
                            }
                        })
                    } else {
                        return
                    }
                });

                this.table.on('click', '[data-role="btn-cn-fields"]', function () {
                    var item_id = $(this).attr('item_id');
                    window.open('{% url "dashboard:fields" %}?item_id='+item_id,
                                '_blank',
                                'height=400,width=600,top=200,left=500,toolbar=no,menubar=no,scrollbars=no,resizable=no,location=0,status=no');
             });


            }
        }


        $(document).ready(function () {

            klass.init()


        });

        function delInput(that) {
            $(that).parent().parent().remove();
        }

        function addInputReturn(that) {
                //添加减号
                var $content = "";
                $content += '<a href="#" onclick="delInput(this)" >';
                $content += '<span class="glyphicon glyphicon-minus"></span>';
                $content += '</a>';
                $(that).parent().append($content);

                //去除加号
                that.remove();

                //增加标签
                var html = "";
                html += '<div class="row">'
                html += '<div class="col-sm-5">'
                html += '<input type="text" name="key"  maxlength="64" class="form-control">'
                html += '</div>'
                html += '<div class="col-sm-5">'
                html += '<input type="text" name="value"   maxlength="64" class="form-control">'
                html += '</div>'
                html += '<div class="col-sm-1">'
                html += '<a href="#" id="dynamic" onclick="addInputReturn(this)"><span class="glyphicon glyphicon-plus"></span></a>'
                html += '</div>'
                html += '<hr>'
                html += '</div>'
                $("#add-fields").last().append(html);
        }

    </script>

{% endblock %}

templates/itemUpdate.html
{% extends 'portal/base.html' %}
{% load static %}
{% load bootstrap %}
{% load mytags %}
{% block title %}编辑{% endblock %}

{% block content %}
    <section class="content-header"></section>
    <section class="content">
    <div class="wrapper" style="width:50%;">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3>修改</h3>
            </div>

            <form method="post" action="{% url 'dashboard:item'%}?id={{ item.id }}" class="form-horizontal">
                {% csrf_token %}
                <div class="box-body">
                    {{ itemf.title | bootstrap_horizontal }}
                    {{ itemf.username | bootstrap_horizontal }}
                    {{ itemf.group | bootstrap_horizontal }}
                    <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2" for="id_password">密码</label>
                        <div class="col-sm-10 col-lg-10">
                            <input type="text" name="password" value="{{ item.str_passwd }}"  maxlength="64" class=" form-control" required="" id="id_password">
                        </div>
                    </div>
                    {{ itemf.url | bootstrap_horizontal }}
                    {{ itemf.comment | bootstrap_horizontal }}
                    <hr>

                </div>
                <div class="box-footer ">
                    <button class="btn btn-success" type="submit" >保存</button>
                    <button class="btn btn-danger" id="back" type="button">返回</button>
                </div>
            </form>
        </div>
    </div>
    </section>
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            $('#back').click(function () {
               window.location.href = "{% url 'dashboard:item-list' %}";
            });
        })
    </script>
{% endblock %}